
# CyberFiles default theme

# If you can, you probably shouldn't edit this file.
# To make a custom theme:
#   - Create a new .yml file in this directory, or duplicate this one
#   - Change the 'theme' config option to the name of your new file
# Once you have your file, any theme variables you set in there will override the ones set here

bg: '#1E1E24'
bg2: "#3f3f45"
fg: '#f3f3fc'
fg2: "#9a9aa2"
fg2H: "#b9b9c1"
accent: "#A3E7FC"
fileSep: +bg2
fileH: +bg2
fileC: "#5e5d65"
fileListHeaders: +fg2
fileIcon: +fg2
fileNameCol: +fg
fileDateCol: +fg2
fileDateMobile: +fg2
fileSizeCol: +fg2
fileListFooter: +fg2
scrollbar: +bg2
scrollbarH: "#5e5d65"
scrollbarC: "#717179"
bgTopbar: +accent
fgTopbar: +bg
fgTopbarH: +bg2
bgTopbarButtonH: '#dbf6fe'
topbarBorder: +bg2
textboxPlaceholder: +fg2
filterBarBottom: +bg2
filterBarBottomF: +accent
filterBarBgF: +bg2
filterBarText: +fg
bgPopup: +bg
fgPopup: +fg
fgPopupButton: +accent
bgPopupButtonH: rgba(163, 231, 252, 0.3)
bgPopupButtonC: rgba(163, 231, 252, 0.5)
hyperlink: +accent
hyperlinkH: +fg2
loadingSpinner: +accent
browserTheme: +bgTopbar