
# Configuration for CyberFiles
# See https://github.com/CyberGen49/CyberFiles2#configuration for documentation

# General settings
language: en
siteName: CyberFiles
siteDesc: Browse and preview server files with ease.
hiddenFiles:
  - '*.php'
  - 'index.html'
  - '.*'
  - '_*'
hideDirWhenContains:
  - 'index.php'
  - 'index.html'
  - '_cf_hideFromList'
headerFileNameMarkdown: _cf_header.md
headerFileNameHtml: _cf_header.html
hideContentsFile: _cf_hideContents
sortFileName: _cf_sortName
sortFileDate: _cf_sortDate
sortFileExt: _cf_sortType
sortFileSize: _cf_sortSize
sortFileDesc: _cf_sortDesc
defaultSort:
  type: name
  desc: false
dateFormatShort: '%b %d, %Y'
dateFormatFull: '%m/%d/%Y %I:%+M %p'
upButtonInFileList: true
mobileFileListBorders: false
videoAutoplay: true
audioAutoplay: true
videoProgressSave:
  enable: true
  minDuration: 600 # 10 minutes
  minPercent: 10
  maxPercent: 90
  expire: 168 # 7 days
  prompt: true
textPreviewMaxSize: 1000000
shortLinkSlugLength: 8
logTimezone: America/Chicago
logUserIpHeader: REMOTE_ADDR

# Colour settings
theme: Default

# Other things
version: v1.10.2