
# Configuration for CyberFiles
# See https://github.com/CyberGen49/CyberFiles2#configuration for documentation

# General settings
language: en
siteName: CyberFiles
siteDesc: View and browse files with ease.
hiddenFiles:
  - '.'
  - '..'
  - '*.php'
  - '*.html'
  - '.*'
  - '_*'
  - 'conf.yml'
  - 'robots.txt'
hideDirWhenContains:
  - 'index.php'
  - 'index.html'
  - '_cf_hideFromList'
dateFormatShort: '%b %d, %Y'
dateFormatFull: '%m/%d/%Y %I:%+M %p'

# Colour settings
theme:
  bg: '#000'
  bg2: "#222429"
  fileSep: "#1a1b1d"
  fileH: "#1f2124"
  fileC: "#32353b"
  scrollbar: "#222429"
  scrollbarH: "#3d4047"
  scrollbarC: "#575a63"
  fg: '#fff'
  fg2: "#6f778b"
  fg2H: "#acb4c7"
  fg3: "#64666c"
  accent: "#35486d"