
# Configuration for CyberFiles
# See https://github.com/CyberGen49/CyberFiles2#configuration for documentation

# General settings
language: en
siteName: CyberFiles
siteDesc: Browse and preview server files with ease.
hiddenFiles:
  - '.'
  - '..'
  - '*.php'
  - '*.html'
  - '.*'
  - '_*'
  - 'conf.yml'
  - 'robots.txt'
hideDirWhenContains:
  - 'index.php'
  - 'index.html'
  - '_cf_hideFromList'
headerFileNameMarkdown: _cf_header.md
headerFileNameHtml: _cf_header.html
hideContentsFile: _cf_hideContents
sortFileName: _cf_sortName
sortFileDate: _cf_sortDate
sortFileSize: _cf_sortSize
sortFileDesc: _cf_sortDesc
dateFormatShort: '%b %d, %Y'
dateFormatFull: '%m/%d/%Y %I:%+M %p'
upButtonInFileList: false
mobileFileListBorders: false
videoAutoplay: true
audioAutoplay: true

# Colour settings
theme: Default

# Other things
version: "2021.09.17"