
# Configuration for CyberFiles
# See https://github.com/CyberGen49/CyberFiles2#configuration for documentation

# General settings
language: en
siteName: CyberFiles
siteDesc: An open sourced file index for the web to make accessing server content easy.
hiddenFiles:
  - '.'
  - '..'
  - '*.php'
  - '*.html'
  - '.*'
  - '_*'
  - 'conf.yml'
  - 'robots.txt'
hideDirWhenContains:
  - 'index.php'
  - 'index.html'
  - '_cf_hideFromList'
headerFileName: _cf_header.md
dateFormatShort: '%b %d, %Y'
dateFormatFull: '%m/%d/%Y %I:%+M %p'
upButtonInFileList: false

# Colour settings
theme: Default